### ISSUE TITLE
ESP32 example

### ISSUE THREAD

**Issue by thijstriemstra** [sekdiy/FlowMeter#17]
I had to change the example slightly, and use `digitalPinToInterrupt`, to make it work on ESP32 using arduino framework:

```cpp
int pin = 21;
attachInterrupt(digitalPinToInterrupt(pin), TestSR, RISING);
// vs attachInterrupt(INT0, TestSR, RISING);
```

**Comment by sekdiy** [comment]
Good idea to improve platform abstraction. 

This change is already resolved in pull request #15, so it will find its way into the master branch soon.
