### ISSUE TITLE
Arduino IDE states 'Category in library FlowMeter is not valid'

### ISSUE THREAD

**Issue by Gr3yh0und** [sekdiy/FlowMeter#3]
## Expected behavior 
Everything is fine while compiling for ESP8266 on the Arduino IDE.

## Observed behavior.
Arduino IDE 1.8.5 reports warning:
> WARNING: Category 'Device Control Sensors Sensor Measurement Liquid Water Flow Meter' in library FlowMeter is not valid. Setting to 'Uncategorized'

**Comment by sekdiy** [comment]
Took me a while to respond, sorry. Swamped with work. Will look into it soon.

**Comment by Gr3yh0und** [comment]
Would be cool if you could merge the two pull requests from @per1234 .
Cheers

**Comment by sekdiy** [comment]
Giving up due to time constraints, accepting without prior tests. ;)
