### ISSUE TITLE
Split up flow sensor and flow meter into different classes and files.

### ISSUE THREAD

**Issue by sekdiy** [sekdiy/FlowMeter#7]
Currently the sensing and the metering functions are merged into one class/object, requiring users to deal with the complexity of the metering interface even if all they need is a simple flow rate value. 

When connecting one or multiple sensors, users should have the choice between a lightweight interface to their hardware and a sophisticated metering solution.

**Comment by kapyaar** [comment]
Hi, Another nice feature would be to add support for sensors with Voltage (analog) and Current (4-20mA) signals in addition to the pulse type.

**Comment by sekdiy** [comment]
Hi @kapyaar, can you recommend any analog frontends and sensors for that purpose? 
Traditionally, current loops are rather difficult to glue to general purpose Arduino/ESP/uC boards. 

I don't have access to voltage or current loop flow sensors, so personally I'm not planning for 10V or 4-20mA compatibility at this time. 

But it sure would be nice to have. :)

**Comment by sekdiy** [comment]
Closed due to inactivity.
